FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04
MAINTAINER CUI Wei <ghostplant@qq.com>

RUN apt update && apt install -y --no-install-recommends openjdk-8-jdk curl git vim-tiny less netcat-openbsd zlib1g-dev bash-completion g++ python3-setuptools python3-pip python3-wheel python3-numpy python3-dev && rm -rf /var/lib/apt/lists/*
RUN curl -Ls https://github.com/bazelbuild/bazel/releases/download/0.10.0/bazel_0.10.0-linux-x86_64.deb > bazel.deb && dpkg -i bazel.deb && rm bazel.deb
RUN cd root && git clone http://github.com/tensorflow/tensorflow --branch r1.6 --single-branch --depth 1
RUN ln -s python3 /usr/bin/python
RUN echo "/usr/local/cuda-8.0/targets/x86_64-linux/lib/stubs" > /etc/ld.so.conf.d/cuda-8.0-stubs.conf && ldconfig
RUN ln -s libdevice.compute_50.10.bc /usr/local/cuda/nvvm/libdevice/libdevice.10.bc

RUN ln -s libcudnn.so.6 /usr/lib/x86_64-linux-gnu/libcudnn.so.6.0
WORKDIR /root/tensorflow

RUN sed -i 's/^#if TF_HAS_.*$/#if !defined(__NVCC__)/g' tensorflow/core/platform/macros.h

RUN /bin/echo -e "/usr/bin/python3\n\nn\nn\nn\nn\nn\nn\nn\nn\nn\ny\n8.0\n/usr/local/cuda\n6.0\n/usr/local/cuda\n\n\nn\n\nn\n-march=native\nn\n" | ./configure

RUN bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
RUN rm -rf /root/tensorflow_pkg && bazel-bin/tensorflow/tools/pip_package/build_pip_package /root/tensorflow_pkg
